### ISSUE TITLE
LDAPPasswordIsMandatoryError when no One-Time password is supplied

### ISSUE THREAD

**Issue by renini** [privacyidea/privacyidea-credential-provider#1]
i'm testing out the credential provider, and so far pretty happy with it.
But i'm having an issue with users that don't have any token enrolled. (its desired for us that some users are allowed to login without token).

Whenever i just enter the Username and Password and leave the One-Time Password field blank in the credential provider i get the following error:

> An error occured, Error Code: 88809008  You could not be authenticated. Wrong username or password?

And in privayidea.log:

> [WARNING][privacyidea.lib.resolvers.LDAPIdResolver:259] failed to check password for u'cn=user1,o=org'/u'cn=user1,o=org': LDAPPasswordIsMandatoryError('password is mandatory in simple bind',)
> [INFO][privacyidea.lib.user:359] user User(login=u'user1', realm=u'realm1', resolver=u'ldapresolver1') failed to authenticate.

Whenever i enter the password besides the Password Field also in in the One-Time Password field it successfully logs in the user.

I have a policy set with the following setting:
{ "passthru": "userstore" }

How can i make sure the credential provider also works by leaving the OTP field blank, this is confusing to have the password entered twice. 
Is this possible, should i configure some setting in the credential provider or the privacyidea backend to support this scenario? Or is this currently not supported?

**Comment by cornelinux** [comment]
This repo is only ment for the documentation for the credential provider.
