### ISSUE TITLE
Image from network path

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-credential-provider#137]
Check if this can be done. Currently, `LoadImageA` does not seem to work with a network path

**Comment by lckrspirit** [comment]
Hi everyone, i checked in my infrasturture. 

First, I uploaded the logo to the shared folder on the domain controller - `\\dc01\klanetagent\mfa-logo.bmp`.  Then, when installing the provider, I specified the same path. 

I checked it on several servers. Given that all computers have access to the domain controller, this works.

**Comment by nilsbehlen** [comment]
great, thanks for sharing this information!
I had not tested that myself yet, so i guess the person telling me did something else wrong - however, this can be closed then.
