### ISSUE TITLE
Tile Image not working as expected

### ISSUE THREAD

**Issue by KommunistGangsta** [privacyidea/privacyidea-credential-provider#138]
Anyone else having problems changing the Tile Logon image on Windows 10 22H2?

I have everything according to the instruction manual (or so I believe), already rebooted the machine, but the custom logo never shows up, it still displays the default logo.

I tripled checked, reinstalled the credential provider, and still uses the default.

The registry has the correct entry 
-------
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Netknights GmbH\PrivacyIDEA-CP

v1_bitmap_path 
REG_SZ 
C:\_logo\hospital_white.bmp
![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/98977577/8db63d9b-a053-427b-ab07-6041be46da47)

------

The directory IS correct (copied from Win Explorer)
C:\_logo\hospital_white.bmp

The file is a BMP, with 128x128 resolution as indicated on the manual.
![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/98977577/82f6fbad-7121-48cd-820f-de4fca525cfb)

And it still shows the default tile
![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/98977577/99ec0789-3c05-4e26-8d3a-9b2c49924776)

Does anyone have a tip of where I may be failing?

**Comment by nilsbehlen** [comment]
Is it really a bitmap or did you just change .png to .bmp?
You can also set debug log to 1, check for these lines
```
[17-08-2023 09:21:44] [CCredential.cpp:333] CCredential::GetBitmapValue
[17-08-2023 09:21:44] [CCredential.cpp:346] (long) -1
[17-08-2023 09:21:44] [CCredential.cpp:380] (long) 0
```
and post them here.

**Comment by KommunistGangsta** [comment]
I created a new 128x128 BMP image on paint.NET, and pasted a PNG logo on it.

Unless paint.NET saves the BMP in an incompatible version...

Here are the log lines you asked for

[01-09-2023 11:13:22] [CCredential.cpp:333] CCredential::GetBitmapValue
[01-09-2023 11:13:22] [CCredential.cpp:346] (long) 32
[01-09-2023 11:13:22] [CCredential.cpp:355] (long) 0
[01-09-2023 11:13:22] [CCredential.cpp:380] (long) 0

**Comment by nilsbehlen** [comment]
hm there is no error but the image is not loaded. `LoadImageA` is very picky unfortunately, so you could try creating that image with Paint, that has always worked for me.

**Comment by KommunistGangsta** [comment]
hmm, in that case i'll try creating one with Paint and see if that works

Cheers

**Comment by KommunistGangsta** [comment]
Which BMP do you usually save in Paint?

16 color, 256 color or 24-bit?

**Comment by nilsbehlen** [comment]
16 iirc, unfortunately you cannot use high quality/transparency....

**Comment by KommunistGangsta** [comment]
Thanks brother! It worked :)
Created with Paint in 16 color (4 bit-depth), and now the logo shows up!

With Paint.NET the BMP was being saved in 32 bit-depth, and apparently is not supported.

Thanks for the help!
