### ISSUE TITLE
Wrong OTP pin

### ISSUE THREAD

**Issue by Mystikal57** [privacyidea/privacyidea-credential-provider#141]
Hi,

When i use test in pi all is okay:
![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/8256583/7ed0a8ff-1221-49d5-b26e-975fcf1ae412)

When i use windows 11 privacyidea credential provider:
![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/8256583/96f12747-857c-4f4c-94d4-fe66ef71ced6)

have you any idea ?

Thank you

**Comment by nilsbehlen** [comment]
Hi,
i dont know what you have entered, how your CP or privacyidea is configured. So no, i dont know.

**Comment by Mystikal57** [comment]
CP is configured by default
Privacyidea by default, i tested totp and hotp.

![image](https://github.com/privacyidea/privacyidea-credential-provider/assets/8256583/c35f76c0-9e55-4d3a-bd37-901a2479f2b8)

**Comment by Mystikal57** [comment]
Oh okay, i understand that i have to type my ldap password in password and pin+otp in otp ?
my password: azerty
my pin 987654
my otp: 123456
i have to enter the otp: 987654123456 ?

**Comment by nilsbehlen** [comment]
yes, you will have to enter your windows password. if everything is default, its pin+otp for the otp field.

**Comment by Mystikal57** [comment]
okay thank you
Is it possible to juste have to enter otp for the otp field ?

**Comment by nilsbehlen** [comment]
you do not have to use a pin for the token

**Comment by Mystikal57** [comment]
wow thank you, I thought it was mandatory
