### ISSUE TITLE
enable_reset Text wrong and not editable

### ISSUE THREAD

**Issue by DarkWiggerl** [privacyidea/privacyidea-credential-provider#145]
Hi, 

unfortunately there is a spelling mistake in the setting "enable reset" (at least in German). It says "Login Zurücksetzten" instead of "Login zurücksetzen". 

Unfortunately, the text is also not editable, which would be great.

**Comment by nilsbehlen** [comment]
Hello,
you are right i will fix that and make the text configurable.

**Comment by nilsbehlen** [comment]
closed by #146
