### ISSUE TITLE
German promt in login window (By default)

### ISSUE THREAD

**Issue by lckrspirit** [privacyidea/privacyidea-credential-provider#150]
**Hi everyone,**

I decided to test the provider in my infrastructure. I noticed such a feature that the default login window is in German.
It was not possible to solve it by simple research. On our forum thread, where they promise to fix this in version **3.5.2**. 

https://community.privacyidea.org/t/credential-provider-changed-prompts-to-german/3305/2 

I'm really looking forward to the new release with this fix.

**Comment by lckrspirit** [comment]
Installed the release provider v.3.4.0, everything works as well.

**Comment by nilsbehlen** [comment]
https://github.com/privacyidea/privacyidea-credential-provider/releases/tag/v3.5.2
