### ISSUE TITLE
SetStatusMessage not working on CPUS_CREDUI

### ISSUE THREAD

**Issue by YiShan8787** [privacyidea/privacyidea-credential-provider#154]
Hi,

I need to use the second-factor function, and it works perfectly in the case of cpus_logon, but in the case of cpus_credui, after entering the password, the system does not pop up a prompt, but I can log in successfully. 

I traced the source code and found that it is pqcws->SetStatusMethod has problems in the case of cpus_credui, I would like to know if there is a way to make the SetStatusMethod work fine.

**Comment by nilsbehlen** [comment]
I dont think i really understand you. You do not get a prompt for the second factor in case of credui? And that is because of 
`pqcws->SetStatusMessage`? How does the rest of your config look?

**Comment by YiShan8787** [comment]
My current config is as follows,

[HKEY_LOCAL_MACHINE\SOFTWARE\NetKnights GmbH\PrivacyIDEA-CP]
"offline_file"="c:\\tmp\\data.json"
"two_step_hide_otp"="1"
"webauthn_preferred"="1"
"two_step_send_password"="0"
"otp_text"="Please enter your second factor!"
"otp_hint_text"="Please enter your second factor!"
"prefill_username"="1"
"show_domain_hint"="1"
"v1_bitmap_path"="c:\\tmp\\test.bmp"
"login_text"="test Login"

Let me briefly explain my problem,
I want the following prompt to appear in RDP, but the system will not pop up the prompt, but it can run.

"Insert your security key!"
"Touch your Security Key!"

**Comment by nilsbehlen** [comment]
yeah, webauthn does not work for credui because it is running in user context. The things that are required to do webauthn only work in system context, which is only for logon/unlock
