### ISSUE TITLE
webauthn_preferred = 1 but I get still asked about the OTP instead of FIDO2 Stick

### ISSUE THREAD

**Issue by jowin202** [privacyidea/privacyidea-credential-provider#155]
Hi,
I registered a OTP and WebAuthn FIDO2 Stick in PrivacyIdea. Howeer, I would like to be asked only for the FIDO2 Stick and not for the OTP, or at least the order should be changed (first FIDO2, and if not available or cancelled, then for the OTP).

I thought setting webauthn_preferred=1 in registry should solve the problem, but it doesn't

kind regards
jowin202

**Comment by nilsbehlen** [comment]
It works like that, if you configured everything correctly and there is no bug (which i dont know of).
Have you set `two_step_send_password` or `two_step_send_empty_pass` to trigger the token?
You can post a log here, but enable debug log in the registry before creating one.

**Comment by jowin202** [comment]
I haven't set `two_step_send_password` or `two_step_send_empty_pass` 

Now, I tested it with setting `two_step_send_empty_pass` and it works exactly as I want (first asking for FIDO token, manual swith to OTP possible), but with one drawback: if I manually switch to OTP it always says "wrong password". I think this is because of sending the empty pass, which is obviously wrong.

Is there a way to **first** ask for the FIDO2 token and (if not available) then allow the OTP token?

I'll prepare logs, but I have to ask for publishing due to privacy reasons.

**Comment by nilsbehlen** [comment]
> Is there a way to first ask for the FIDO2 token and (if not available) then allow the OTP token?
No there is not. You need to have your config in privacyidea in order for you use-case. You probably want to set the type of OTP token you use to challenge-response via a policy and then have the token use the same PIN as the webauthn token
