### ISSUE TITLE
Activate 2fa after sleeping mode or the screensaver

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea-credential-provider#156]
For the moment, cpus_unlock allows managing 2fa when locking or unlocking a session.

Could we have the option to activate or not 2fa when either when the screen goes black and when the user closes the session?

**Comment by nilsbehlen** [comment]
so what you want me to do?

**Comment by nilsbehlen** [comment]
this is the same as #131.
We might do that at some point in the future when we have time for that.
