### ISSUE TITLE
If you have 3 tokens, you get 3 times the OTP text displayed 

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea-credential-provider#157]
When challenge response token are used with the CP the Privacyidea server generated a message per token. So if you have 3 token that were triggered, the credential provider displays then 3 times the same message.

Could it be possible to display only 1 message?

This issue is similar to this one:
https://github.com/privacyidea/privacyidea-credential-provider/issues/144

**Comment by nilsbehlen** [comment]
in a first, simple approach, the credential provider could eliminate duplicates in the messages

**Comment by EchedelleLR** [comment]
This happens in privacyIDEA 3.9.3 yet.

**Comment by nilsbehlen** [comment]
Yes, because it has been improved in privacyidea 3.10 or 3.5.4 of this plugin
