### ISSUE TITLE
Hide the domain name in lock screen

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-credential-provider#16]
The following thing should be configurable:

When the desktop is locked, the domain name of the user should be hidden.
I.e. the user ``user@domain`` locks the desktop.

Usually ``user@domain`` is displayed on the lock screen.
We can now however hide the complete user name.

It would be good to be able to only display ``user`` without the domain.

# Why is that?

Users are domain users and login with only the username ``user``. They are not aware of ``domain``.
So this is a simply convenience function, that the users see their username, but are not puzzled by the domain name.

**Comment by nilsbehlen** [comment]
This feature should be mutually exclusive to hiding the whole username right? 
While this can be done in the installer to have 2 mutually exclusive checkboxes, it will still be possible to change registry afterwards. In that case which option should outweigh the other?

**Comment by cornelinux** [comment]
I think if you say "hide domain".
**And** if you say "hide username" in spoken language we would expect, that everything is hidden. 
As we do not say "hide domain, but show username".
(So I think they are not really exclusive ;-)

So the "hide username" (old function) should outweigh.

**Comment by cornelinux** [comment]
Closed by #17
