### ISSUE TITLE
Support password_expired and mustChange

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-credential-provider#20]
Support CPUS_CHANGE_PASSWORD
needs gui and endpoint implementation

**Comment by nilsbehlen** [comment]
The CP needs to switch to CPUS_CHANGE_PASSWORD after detecting a PASSWORD_MUST_CHANGE or PASSWORD_EXPIRED in the ntStatus/ntSubStatus.

**Comment by nilsbehlen** [comment]
Since that doesnt really work, a dialog is opened to ask for the new password, then the password is changed and the user is automatically logged in.
The case CPUS_CHANGE_PASSWORD is unsupported now (= handled by windows), because it is only used when a user actively wants to change the password. We dont need a second factor for that scenario, since the user must have been logged in (with the second factor) beforehand.

**Comment by cornelinux** [comment]
Closed by #25

**Comment by nilsbehlen** [comment]
The problem persists for expired passwords on locked machines.

**Comment by nilsbehlen** [comment]
closed by #32
