### ISSUE TITLE
Log In Failed: Error code 88809007 Serive could not handle the request.

### ISSUE THREAD

**Issue by TylerByte666** [privacyidea/privacyidea-credential-provider#23]
Hi, please help me.

I have enrolled my user token but when I try use the credential provider on a windows 10 x64 Client it does not work. Error code in Title. I have compiled & installed the x64 debug version. The log file says:

"result:" {"status": false, "error":{"message":"SubscriptionError('No subscription for your client.', application=privacyidea-cp,"code": -500)"}} .. at line 648 'endpoint.cpp'

The user is from an ldap resolver and testing the OTP on the web UI works. Thank you for your time.

**Comment by TylerByte666** [comment]
Thank you man. So it is Enterprise License we need?

**Comment by nilsbehlen** [comment]
It depends on your needs, you can use the contact form (or email) on our site to get in touch and you can probably get a test subscription too
