### ISSUE TITLE
MSI package

### ISSUE THREAD

**Issue by mr-crux** [privacyidea/privacyidea-credential-provider#44]
Hello,
Documentation at github repository (privacyidea-credential-provider/doc/installation.rst) states, that "The privacyIDEA Credential Provider comes as a 32bit and 64bit MSI package."

But I found no msi package at this repository. May be someone can guide me we I can find it?

**Comment by nilsbehlen** [comment]
Hi,
you would have to build it from source yourself. 
For the MSI, as the installation doc states:

"Ask the company NetKnights to get an evaluation version of the privacyIDEA Credential Provider [2]."
