### ISSUE TITLE
Windows 10 Support?

### ISSUE THREAD

**Issue by wwalker0307** [privacyidea/privacyidea-credential-provider#46]
Does the available source code support Windows 10?  I've compiled the code and ran the installer on Windows 10 1709 and Windows 10 1809, but it doesn't give the option to log in with PrivacyIDEA.  I've also reinstalled and made it the default authentication provider but it still doesn't work.

I see the registry entries under HKLM\SOFTWARE\WOW6432Node\Netknights GmbH\PrivacyIDEA-CP, but not the entries under CLSID.

I compiled the installer using Visual Studio 2017 and retargeted the project to SDK 10.0.17763.0 and Platform Toolset v141.  Using the most recent version of rapidjson and Wix 3.11

**Comment by nilsbehlen** [comment]
Hi, yes the code supports Windows 10.
You will at least need the entry at HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Providers\{7BAF541E-F8E0-4EDF-B69A-BD2771139E8E} with the default name and value 'PrivacyIDEACredentialProvider'.
For the filter it's: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{34065473-D75F-4BC2-9782-E98E63ED0D41} with value 'PrivacyIDEACredentialProviderFilter'.

**Comment by HarryKodden** [comment]
Hi I experienced same issue. I did add the RegEdit entries, but Credential Provider does not show. 

I compiled the installer using Visual Studio 2019 and retargeted the project to SDK 10.0.17763.0 and Platform Toolset v142. Using the most recent version of rapidjson and Wix 3.11

**Comment by nilsbehlen** [comment]
Hi, have you tried using this file:
https://github.com/privacyidea/privacyidea-credential-provider/blob/master/CredentialProvider/Register.reg
or checked if the entries from it are made?
Which version of windows are you using?
I was not able to reproduce this at any time

**Comment by HarryKodden** [comment]
Yes ! I have added the Reg Entries as specified and verified via RegEdit that the entries do show up in the registry.
I am using Windows 10 Pro. OS Build 17134.1

**Comment by nilsbehlen** [comment]
Have you checked if you set any policies regarding credential providers?
Is the PrivacyIDEACredentialProvider.dll located in system32?
