### ISSUE TITLE
Deadlock is possible

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-credential-provider#53]
in the following scenario:
* Using the filter
* Using 2 step

If the user is not found in any realm, it is not possibie to go back to the first step to change the username, instead it stays in the second step.

**Comment by massaeg** [comment]
Dear Sir,
Kindly I need to know if your compile the privacyidea credential provider software , and please if yes can you give me copy.

Thanks

**Comment by nilsbehlen** [comment]
closed via #54
