### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by Elleni57** [privacyidea/privacyidea-credential-provider#57]
Trying to compile with VS2019. I have installed wix toolset v3.11.02 and its VS2019 extension, and have added nlohmann/json.hpp in CppClientCore. 

How can I solve the following compile failures?
1>------ Build started: Project: CppClientCore, Configuration: Debug Win32 ------
2>------ Build started: Project: CredentialProviderFilter, Configuration: Debug Win32 ------
1>Challenge.cpp
2>Dll.cpp
2>CCredentialProviderFilter.cpp
2>C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\CCredentialProviderFilter.h(25,10): fatal error C1083: Cannot open include file: 'helpers.h': No such file or directory
2>guid.cpp
2>Generating Code...
2>Done building project "CredentialProviderFilter.vcxproj" -- FAILED.
1>Endpoint.cpp
1>Logger.cpp
1>OfflineData.cpp
1>OfflineHandler.cpp
1>PrivacyIDEA.cpp
1>RegistryReader.cpp
1>Generating Code...
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\username\source\repos\privacyidea-credential-provider\Debug\CppClientCore.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "CppClientCore.vcxproj" -- FAILED.
3>------ Build started: Project: CredentialProvider, Configuration: Debug Win32 ------
3>Configuration.cpp
3>C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\Configuration.h(21,10): fatal error C1083: Cannot open include file: 'PIConf.h': No such file or directory
3>CCredential.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h(167,10): fatal error C1083: Cannot open include file: 'excpt.h': No such file or directory
3>CProvider.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h(167,10): fatal error C1083: Cannot open include file: 'excpt.h': No such file or directory
3>Dll.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h(167,10): fatal error C1083: Cannot open include file: 'excpt.h': No such file or directory
3>guid.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt.h(10,10): fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
3>helpers.cpp
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h(167,10): fatal error C1083: Cannot open include file: 'excpt.h': No such file or directory
3>Utilities.cpp
3>C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\Configuration.h(21,10): fatal error C1083: Cannot open include file: 'PIConf.h': No such file or directory
3>Generating Code...
3>Done building project "CredentialProvider.vcxproj" -- FAILED.
4>------ Build started: Project: WiXSetup, Configuration: Debug x86 ------
4>		C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe -dDebug -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\" -dSolutionDir=C:\Users\username\source\repos\privacyidea-credential-provider\ -dSolutionExt=.sln -dSolutionFileName=PrivacyIDEA-CredentialProvider.sln -dSolutionName=PrivacyIDEA-CredentialProvider -dSolutionPath=C:\Users\username\source\repos\privacyidea-credential-provider\PrivacyIDEA-CredentialProvider.sln -dConfiguration=Debug -dOutDir=bin\x86\Debug\ -dPlatform=x86 -dProjectDir=C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\ -dProjectExt=.wixproj -dProjectFileName=WiXSetup.wixproj -dProjectName=WiXSetup -dProjectPath=C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\WiXSetup.wixproj -dTargetDir=C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\bin\x86\Debug\ -dTargetExt=.msi -dTargetFileName=privacyIDEACredentialProviderSetup.msi -dTargetName=privacyIDEACredentialProviderSetup -dTargetPath=C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\bin\x86\Debug\privacyIDEACredentialProviderSetup.msi -dCredentialProviderFilter.Configuration=Debug -d"CredentialProviderFilter.FullConfiguration=Debug|Win32" -dCredentialProviderFilter.Platform=Win32 -dCredentialProviderFilter.ProjectDir=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\ -dCredentialProviderFilter.ProjectExt=.vcxproj -dCredentialProviderFilter.ProjectFileName=CredentialProviderFilter.vcxproj -dCredentialProviderFilter.ProjectName=CredentialProviderFilter -dCredentialProviderFilter.ProjectPath=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\CredentialProviderFilter.vcxproj -dCredentialProviderFilter.TargetDir=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\bin\Win32\Debug\ -dCredentialProviderFilter.TargetExt=.dll -dCredentialProviderFilter.TargetFileName=CredentialProviderFilter.dll -dCredentialProviderFilter.TargetName=CredentialProviderFilter -dCredentialProviderFilter.TargetPath=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\bin\Win32\Debug\CredentialProviderFilter.dll -dCredentialProvider.Configuration=Debug -d"CredentialProvider.FullConfiguration=Debug|Win32" -dCredentialProvider.Platform=Win32 -dCredentialProvider.ProjectDir=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\ -dCredentialProvider.ProjectExt=.vcxproj -dCredentialProvider.ProjectFileName=CredentialProvider.vcxproj -dCredentialProvider.ProjectName=CredentialProvider -dCredentialProvider.ProjectPath=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\CredentialProvider.vcxproj -dCredentialProvider.TargetDir=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\bin\Win32\Debug\ -dCredentialProvider.TargetExt=.dll -dCredentialProvider.TargetFileName=CredentialProvider.dll -dCredentialProvider.TargetName=CredentialProvider -dCredentialProvider.TargetPath=C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\bin\Win32\Debug\CredentialProvider.dll -out obj\Debug\ -arch x86 -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" ConfigurationDlgs.wxs Product.wxs
4>		C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe -out C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\bin\x86\Debug\en-us\privacyIDEACredentialProviderSetup.msi -pdbout C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\bin\x86\Debug\en-us\privacyIDEACredentialProviderSetup.wixpdb -cultures:en-us -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -loc ConfigurationDlgsLocales.wxl -sice:ICE09 -contentsfile obj\Debug\WiXSetup.wixproj.BindContentsFileListen-us.txt -outputsfile obj\Debug\WiXSetup.wixproj.BindOutputsFileListen-us.txt -builtoutputsfile obj\Debug\WiXSetup.wixproj.BindBuiltOutputsFileListen-us.txt -wixprojectfile C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\WiXSetup.wixproj obj\Debug\ConfigurationDlgs.wixobj obj\Debug\Product.wixobj
4>C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\Product.wxs(195,0): error LGHT0103: The system cannot find the file 'C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProvider\bin\Win32\Debug\CredentialProvider.dll'.
4>C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\Product.wxs(249,0): error LGHT0103: The system cannot find the file 'C:\Users\username\source\repos\privacyidea-credential-provider\CredentialProviderFilter\bin\Win32\Debug\CredentialProviderFilter.dll'.
4>C:\Users\username\source\repos\privacyidea-credential-provider\WiXSetup\Product.wxs(152,0): error LGHT0103: The system cannot find the file 'C:\Users\username\source\repos\privacyidea-credential-provider\lib\merge\Microsoft_VC142_DebugCRT_x86.msm'.
4>Done building project "WiXSetup.wixproj" -- FAILED.
4>
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

A local search revealed that I have three excpt.h and vcruntime.h files in the following directories: 

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include

PIConf.h is there too (in CppClientCore)

**Comment by massaeg** [comment]
Dear Sir,
Kindly I have same error, did you solve it or not.
Thanks

**Comment by Elleni57** [comment]
Not yet, right now I am trying to compile v2.5.2 where I seem to have more luck. 

The remaining errors are: 

3>resources.rc(11): fatal error RC1015: cannot open include file 'include'.
3>
4>CCredential.cpp
3>Done building project "CredentialProviderFilter.vcxproj" -- FAILED.

5>C:\Users\username\source\repos\privacyidea-credential-provider-2.5.2\WiXSetup\Product.wxs(59,0): error LGHT0103: The system cannot find the file 'C:\Users\Nils\Desktop\privacyidea-credentialprovider-git2\icon.ico'.
5>C:\Users\username\source\repos\privacyidea-credential-provider-2.5.2\WiXSetup\Product.wxs(245,0): error LGHT0103: The system cannot find the file 'C:\Users\username\source\repos\privacyidea-credential-provider-2.5.2\CredentialProviderFilter\bin\Win32\Debug\CredentialProviderFilter.dll'.
5>Done building project "WiXSetup.wixproj" -- FAILED.
5>
========== Build: 3 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by massaeg** [comment]
thanks for your replay ,
can you please let me know how i can add nlohmann/json.hpp in CppClientCore.
i have install vs 2019
- they can give us this dll file or not CredentialProviderFilter.dll

**Comment by Elleni57** [comment]
See under dependencies. There you can grab the file and put it in the mentioned folder. I have done that, but that does not solve the reported error.

**Comment by nilsbehlen** [comment]
Hello,
the solution to the problem is mentioned in the compiler output:
The system cannot find the file 'C:\Users\Nils\Desktop\privacyidea-credentialprovider-git2\icon.ico'.
Change the path to your icon.ico. 
The same goes for the original post:
 fatal error C1083: Cannot open include file: 'helpers.h': No such file or directory
Fix the include path to include the directory of helpers.h...

**Comment by Elleni57** [comment]
Hi Nils and thanks for your reply. What about Helpers.lib?

**Comment by nilsbehlen** [comment]
You cannot start this "program", it is not an executable.

**Comment by Elleni57** [comment]
Only asked as debug of VS2019 spit that one out. Nevermind. I'll check if I succeed with the mentioned solution of changing the corresponding paths and will report back. Thanks again.
