### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by subu1979** [privacyidea/privacyidea-credential-provider#6]
Hi,
i'am getting following error when i compiled the project using Visual Studio 2017

Severity	Code	Description	Project	File	Line	Suppression State
Error		The extension '..\CredentialProviderFilter\bin\x64\Debug\CredentialProviderFilter.dll' could not be loaded because of the following reason: Could not load file or assembly 'file:///D:\privacyidea-credential-provider-master\CredentialProviderFilter\bin\x64\Debug\CredentialProviderFilter.dll' or one of its dependencies. The module was expected to contain an assembly manifest.	WiXSetup	candle.exe	0	

Regards
Subramaniyam.KMV

**Comment by nilsbehlen** [comment]
Hey,
did you build libcurl and did you add rapidjason to the /lib folder of the project?

**Comment by subu1979** [comment]
yes i have done.

**Comment by nilsbehlen** [comment]
With which toolset are you building? VS2015 v140?
Are you able to build the Filter alone?

I didn't encounter this error yet, can you post the whole Error List?

**Comment by subu1979** [comment]
Hi
I'm Using VS 2017 V140

Severity	Code	Description	Project	File	Line	Suppression State
Error		The system cannot find the file 'D:\privacyidea-credential-provider-master\CredentialProvider\bin\Win32\Debug\CredentialProvider.dll'.	WiXSetup	D:\privacyidea-credential-provider-master\WiXSetup\Product.wxs	181	
Error	LNK2019	unresolved external symbol "long __cdecl UnicodeStringInitWithString(unsigned short *,struct _LSA_UNICODE_STRING *)" (?UnicodeStringInitWithString@@YAJPAGPAU_LSA_UNICODE_STRING@@@Z) referenced in function "long __cdecl General::Logon::KerberosChangePassword(enum _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE *,struct _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION *,unsigned short *,unsigned short *,unsigned short *,unsigned short *)" (?KerberosChangePassword@Logon@General@@YAJPAW4_CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE@@PAU_CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION@@PAG222@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\general.obj	1	
Error	LNK2019	unresolved external symbol "long __cdecl KerbInteractiveUnlockLogonInit(unsigned short *,unsigned short *,unsigned short *,enum _CREDENTIAL_PROVIDER_USAGE_SCENARIO,struct _KERB_INTERACTIVE_UNLOCK_LOGON *)" (?KerbInteractiveUnlockLogonInit@@YAJPAG00W4_CREDENTIAL_PROVIDER_USAGE_SCENARIO@@PAU_KERB_INTERACTIVE_UNLOCK_LOGON@@@Z) referenced in function "long __cdecl General::Logon::KerberosLogon(enum _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE * &,struct _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION * &,enum _CREDENTIAL_PROVIDER_USAGE_SCENARIO,unsigned short *,unsigned short *,unsigned short *)" (?KerberosLogon@Logon@General@@YAJAAPAW4_CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE@@AAPAU_CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION@@W4_CREDENTIAL_PROVIDER_USAGE_SCENARIO@@PAG33@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\general.obj	1	
Error	LNK2019	unresolved external symbol "long __cdecl ProtectIfNecessaryAndCopyPassword(unsigned short const *,enum _CREDENTIAL_PROVIDER_USAGE_SCENARIO,unsigned short * *)" (?ProtectIfNecessaryAndCopyPassword@@YAJPBGW4_CREDENTIAL_PROVIDER_USAGE_SCENARIO@@PAPAG@Z) referenced in function "long __cdecl General::Logon::KerberosLogon(enum _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE * &,struct _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION * &,enum _CREDENTIAL_PROVIDER_USAGE_SCENARIO,unsigned short *,unsigned short *,unsigned short *)" (?KerberosLogon@Logon@General@@YAJAAPAW4_CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE@@AAPAU_CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION@@W4_CREDENTIAL_PROVIDER_USAGE_SCENARIO@@PAG33@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\general.obj	1	
Error	LNK2019	unresolved external symbol "long __cdecl DomainUsernameStringAlloc(unsigned short const *,unsigned short const *,unsigned short * *)" (?DomainUsernameStringAlloc@@YAJPBG0PAPAG@Z) referenced in function "long __cdecl General::Logon::CredPackAuthentication(enum _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE * &,struct _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION * &,enum _CREDENTIAL_PROVIDER_USAGE_SCENARIO,unsigned short *,unsigned short *,unsigned short *)" (?CredPackAuthentication@Logon@General@@YAJAAPAW4_CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE@@AAPAU_CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION@@W4_CREDENTIAL_PROVIDER_USAGE_SCENARIO@@PAG33@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\general.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_global_init referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_global_cleanup referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_strerror referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_init referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_setopt referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_perform referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_cleanup referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK2019	unresolved external symbol __imp__curl_easy_getinfo referenced in function "long __cdecl Endpoint::Concrete::SendRequestToServer(struct Endpoint::Concrete::BufferStruct * &,char *,int,char *)" (?SendRequestToServer@Concrete@Endpoint@@YAJAAPAUBufferStruct@12@PADH1@Z)	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\endpoint.obj	1	
Error	LNK1120	12 unresolved externals	CredentialProvider	D:\privacyidea-credential-provider-master\CredentialProvider\bin\Win32\Debug\CredentialProvider.dll	1

**Comment by nilsbehlen** [comment]
there seems to be an issue with curl (the LNK2019). You can try the newer version i uploaded some minutes ago, it uses winhttp instead and should be easier to compile.

**Comment by subu1979** [comment]
Hi 
Thanks for your help. I have downloaded the latest code, but we need to remove the libcurl reference from the linker section.

Any how i was able to build the setup. I will test and update the status.

Thanks & Regards
Subramanyam

**Comment by cornelinux** [comment]
Great that the building of the code worked out!
So the original issue is closed - code works.

Please take a look at documentation to understand the working of this credential provider (not a GINA!).
http://privacyidea-credential-provider.readthedocs.io/en/latest/

Please also note, that we provide professional services and service level agreements, if you want to run the credential provider and privacyIDEA in a bigger, professional setup.
https://netknights.it/en/produkte/privacyidea-credential-provider/
