### ISSUE TITLE
Error LNK2019

### ISSUE THREAD

**Issue by multiOTP** [privacyidea/privacyidea-credential-provider#74]
Hello,
I installed VS2019 and Wix v3.11.02. 
I copied the json-develop\json-develop\single_include\json.hpp to privacyidea-credential-provider-master\CppClientCore\nlohmann

However when I treid to build the solution in VS2019, I get this error :
`LNK2019	symbole externe non résolu _main référencé dans la fonction "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	CppClientCore	C:\Data\privacyidea-credential-provider-master\privacyidea-credential-provider-master\CppClientCore\CppClientCore\MSVCRTD.lib(exe_main.obj)	1	
`

Can you please help me resolve it ?

Thanks a lot for your help

**Comment by multiOTP** [comment]
I changed the build options to "Release" and "Mixed Platforms" and I installed all the 142 Spectre the error is now gone but I am left with :
`RC1015	cannot open include file 'version.h'.	CredentialProviderFilter	C:\Data\privacyidea-credential-provider-master\privacyidea-credential-provider-master\CredentialProviderFilter\resources.rc	11	
`
And some other unable to open include files

Thanks for your help

**Comment by nilsbehlen** [comment]
Hi,
the architecture should be x64 (x86 should still be working too). Then you want to build the WiXSetup project, which will also require the VC142 merge modules in the folder ``lib\merge\``, namely ``Microsoft_VC142_CRT_x64.msm`` for the release configuration.

**Comment by multiOTP** [comment]
When I open the project in VS2019, it says that the wix is incompatible. In my understanding I had to first compile the c++ then do the wix. Is this correct ?

**Comment by nilsbehlen** [comment]
If you build the wix, the dlls will be built automatically beforehand because the wix depends on them. You can also build the CredentialProvider(Filter) projects by themselves which will produce the dlls.

**Comment by multiOTP** [comment]
Ok, I understand but could you tell me wich version of VS to use because with the 2019 it says that it's not a compatible with the wix project. Thanks for your precious help

**Comment by lrowe8** [comment]
You will need to install the Wix Extension for VS2019.
https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2019Extension

**Comment by multiOTP** [comment]
tried that but doesn't work, I still get : 
![image](https://user-images.githubusercontent.com/9338189/98953909-8b75a180-24fd-11eb-9946-bc6f91de53bd.png)

Thanks for your help.

**Comment by multiOTP** [comment]
I might be able to run it from command line but I have to provide the values for all the wix variables. Could you tell me what value they should have ?

**Comment by multiOTP** [comment]
Get command line working a bit further
`
"%wix%bin\candle" *.wxs -o obj\ -dPlatform=x64 -dSolutionDir="C:\Data\privacyidea-credential-provider-master\privacyidea-credential-provider-master" -dConfiguration=build -dCredentialProvider.TargetFileName=CredentialProvider.dll -dCredentialProvider.TargetPath="C:\Data\privacyidea-credential-provider-master\privacyidea-credential-provider-master\CredentialProvider\bin\x64\Release" -dCredentialProvider.TargetName=CredentialProvider -dCredentialProviderFilter.TargetFileName=CredentialProviderFilter -dCredentialProviderFilter.TargetPath="C:\Data\privacyidea-credential-provider-master\privacyidea-credential-provider-master\CredentialProviderFilter\bin\x64\Release" -dCredentialProviderFilter.TargetName=CredentialProviderFilter
`
Then

`"%wix%bin\light" obj\*.wixobj -o bin\commandLineInstaller.msi`

Give me the error : 
`Product.wxs(311) : error LGHT0094 : Unresolved reference to symbol 'WixUI:WixUI_FeatureTree' in section 'Product:*'.`

Any idea how to solve it ?

**Comment by nilsbehlen** [comment]
Hi, if you just want to test it, you can get the prebuild MSI [here](https://github.com/privacyidea/privacyidea-credential-provider/releases).
