### ISSUE TITLE
Do not show the user on the lock screen

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-credential-provider#8]
It should be configurable to not show the user on the lock screen.

I.e. show that the screen is locked, but do not display the information by whom.

**Comment by nilsbehlen** [comment]
I have implemented this now, but it raises a question:
When using the feature the loginname defaults to privacyIDEA Login. Do we want to keep it like this or should i completly remove it?

**Comment by cornelinux** [comment]
I added some comments in the commit.

Does the custom login text also appear during the lock screen? Honestly I do not quite get it - you problem need to show it.
