### ISSUE TITLE
this tool is not secure!

### ISSUE THREAD

**Issue by theoneandonly-vector** [privacyidea/privacyidea-credential-provider#86]
I am able to circumvent this tool with a 100% success rate.

If you use mRemoteNG or similar tools which can save the Windows-creds, you can just readjust the window size after it asks for the OTP -> after the reconnect it won't ask and you get full access to the desktop.

**Comment by theoneandonly-vector** [comment]
setting "two_step_hide_otp" -> 0 doesn't fix this.

**Comment by nilsbehlen** [comment]
do you have the filter enabled?

**Comment by nilsbehlen** [comment]
what are the steps to reproduce this. I cannot do it with mremoteng

**Comment by theoneandonly-vector** [comment]
filter?

steps to reproduce using privacyidea-credential-provider 3.1.1 & mRemoteNG 1.76:
1. create an rdp-connection with saved credentials.
2. connect to the rdp
3. resize the mRemoteNG-window
4. wait for the reconnect

**Comment by nilsbehlen** [comment]
i still can not reproduce this. I do not get a reconnect when resizing the window.
Do you have the filter enabled?

**Comment by theoneandonly-vector** [comment]
what filter? is it configurable using regedit (I don't see an option named filter there)?

**Comment by nilsbehlen** [comment]
you can set it in the component view of the installer. If you missed that, take a look at the registry helpers folder:
https://github.com/privacyidea/privacyidea-credential-provider/blob/master/RegistryHelpers/RegisterFilter.reg

Without the filter, the rdp target will use the default credential provider instead of this one.

**Comment by theoneandonly-vector** [comment]
when I select "default provider" in the setup = it's the same?

**Comment by nilsbehlen** [comment]
yes

**Comment by theoneandonly-vector** [comment]
then I can say "yes"

**Comment by theoneandonly-vector** [comment]
![rdsprivacyidea](https://user-images.githubusercontent.com/10380051/121004830-6abdb380-c78f-11eb-804f-b92e179a189e.gif)

**Comment by nilsbehlen** [comment]
I do not get reconnects if i resize the window in v1.76. However, i do not see how this is a problem of the credential provider if the filter is enabled. You could try to disable the system cp via group policy. Which version of windows are you using and is up to date?

**Comment by theoneandonly-vector** [comment]
"You could try to disable the system cp via group policy" how? :)
so you think this is a problem for all OTP-solutions (on windows)?

Server 2019, I'm updating it rn. but it has the april-update.

**Comment by theoneandonly-vector** [comment]
wtf.. the update actually fixed this.. I'm wondering if there is a CVE for that

**Comment by nilsbehlen** [comment]
Ah thats nice to hear. I hope there was a cve for that since that behavior would break any other credential provider

**Comment by theoneandonly-vector** [comment]
no it will not allow resizing of th elogin-screen anymore.
