### ISSUE TITLE
windows RDWeb html5-webclient compatiblity

### ISSUE THREAD

**Issue by theoneandonly-vector** [privacyidea/privacyidea-credential-provider#87]
when I access the serve rusing the RDWeb html5-webclient sometime sit asks me for the OTP and sometimes it just crashes.

"/RDWeb/webclient/"

**Comment by theoneandonly-vector** [comment]
it only works when I hit "show details". maybe I need to create some sort of login-app which launches the login screen?

**Comment by nilsbehlen** [comment]
i have never heard of that client. Show details of what?

**Comment by theoneandonly-vector** [comment]
this is the client:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin

![image](https://user-images.githubusercontent.com/10380051/120998190-237ff480-c788-11eb-928a-e482af20f3d2.png)

**Comment by theoneandonly-vector** [comment]
show details:
![image](https://user-images.githubusercontent.com/10380051/120998317-48746780-c788-11eb-9dd3-bc0cabb33a93.png)

**Comment by theoneandonly-vector** [comment]
when I disable the privacyidea I don't need to click "show details" but as soon as it's activated I need to click "show details" otherwise it won't ask for the OTP and just keep spinning.

**Comment by nilsbehlen** [comment]
interesting tool. I will look into this when i find the time to set it up.

**Comment by theoneandonly-vector** [comment]
maybe I can inject a js to automatically "click" it.

**Comment by theoneandonly-vector** [comment]
maybe it's possible to use radius so I can use the password filed for password + 2fa or something else? maybe even SAML.. to make this obsolete?

**Comment by nilsbehlen** [comment]
To do what? 
Take a look at https://github.com/privacyidea, maybe you will find something for your requirements
